### ISSUE TITLE
Add support for Jetson Nano

### ISSUE THREAD

**Issue by BioGeek** [robocarstore/donkeycar_controller#1]
Please add support for the Jetson Nano board.

I have a donkeycar with such a board, so if you could guide me in showing where things need to be changed, I would be happy to contribute.

**Comment by BioGeek** [comment]
I created a [similar issue in the donkeycar-console repository](https://github.com/robocarstore/donkeycar-console/issues/1), because that's probably where the changes will need to be made.

**Comment by sctse999** [comment]
Sorry we aren't going to support Jetson for the mobile app. closing this issue now.
