### ISSUE TITLE
Battery

### ISSUE THREAD

**Issue by tillwenke** [robocarstore/donkeycar_controller#10]
Is this feature still present? I am using a MM1 indeed but nothing like this can be found in the app.

Thank you

**Comment by sctse999** [comment]
We have removed the battery status in the app becoz mm1 is discontinued by the manufacturer. You can still check this via donkey car console vehicle status. Go to http://donkey-ip:8000/vehicle/status

**Comment by tillwenke** [comment]
cool thank you. 
Do you have any experience with how accurate the values are. I assume it is % and it give 25 (%) for a 7.4V / 8 V LiPo battery.
[but probably thats not a question for you]

**Comment by sctse999** [comment]
I think we have used 7V as the min and 8.4 as the max and come up with a percentage. The battery voltage decrease in a non-linear style  so it is just a rough figure.

**Comment by tillwenke** [comment]
thx... after a while now :) can you say, how those values (probably from the INA current sensor) are retrieved? And is there already smth in the donkeycar code that does so or is it implemented in the donkeycar controller? 
Thank you

**Comment by sctse999** [comment]
Check here:

https://github.com/robocarstore/donkeycar-console/blob/dev/dkconsole/vehicle/vehicle_service.py#L702

**Comment by tillwenke** [comment]
that was super helpful thx
