### ISSUE TITLE
iphone7 or 8,when tap Drive,no Response

### ISSUE THREAD

**Issue by xuxer** [robocarstore/donkeycar_controller#2]
Hi,thanks for your work！
But I have met something wrong when I  check it with my PI4.(2G and 4G)
The car could listen to me when I "Calibration",but when I tap "Drive",There is no response.

**Comment by sctse999** [comment]
Can you go to the juypter lab service on http://<pi_ip_address>:8888

type the command 
`python manage.py drive` and post the result?

**Comment by xuxer** [comment]
OH,I made it today！I  choice "PICAM”,that's success！but only "PICAM" could work~~
if choice "WEBCAM",it doesn't work！
Let me follow your advice  and try it with “WEBCAM”
