### ISSUE TITLE
Raspberry Pi best model?

### ISSUE THREAD

**Issue by Schultzy1310** [robocarstore/donkeycar_controller#4]
I was able to get this working with a Pi 3B, by editing the WPA Supplicant to have an external WiFi network bridging the iOS device and the Raspberry Pi / Donkey. 

Although this works, I want to upgrade the raspberry pi. 
But how much RAM is needed? I don't want to buy an 8GB ram model when a 2GB model will do the purpose.

Thanks for your awesome work! My students like driving the donkeys!

**Comment by sctse999** [comment]
Hi thanks for the kind words. A Pi 4B 2GB will work great.
