### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by takashiyamanoue** [robocarstore/donkeycar_controller#7]
This is not an issue. 
We are making a ride-able donkey car using this mobile app.
We succeeded to drive the car automatically.
Thank you very much!
Here is the video.
[video](https://www.youtube.com/watch?v=ZMaf031U8jg)
If here is not the appropriate place to post, I will delete this message and re-submit this message at the appropriate place.

**Comment by sctse999** [comment]
Thanks a lot for the kind word!
