### ISSUE TITLE
Problems with the App

### ISSUE THREAD

**Issue by Florian1979** [robocarstore/donkeycar_controller#8]
Hello,

I'm using a PiRacer Pro with RPI 4 4GB and managed to drive the car with the app and record the images. But I'm unable to see the recorded data or the histogram. It always show "no data", despite having recorded more than 2.500 images.  Car path is set to default. I was using the virtual joystick, picam and the servo-esc controller. It is the same for android and iOS App.

What's wrong and how to fix it?

Thanks so much and Best

Florian

**Comment by sctse999** [comment]
Sorry we do not have any plan to support PiRacer or PiRacer Pro.
